services:
  - type: web
    name: api-products
    runtime: docker
    port: 8080
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: ${POSTGRES_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: ${POSTGRES_USERNAME}
      - key: SPRING_DATASOURCE_PASSWORD
        value: ${POSTGRES_PASSWORD}
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update

databases:
  - name: products_db
    plan: free
    databaseName: products_db
    user: postgres
